networks:
  fw_network:

volumes:
  # fw_pgsql_data:
  fw_prometheus_data:
  fw_grafana_data:

services:

  api:
    container_name: framework_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/framework_api
    networks:
      - fw_network

  # db:
  #   container_name: mariadb-database
  #   image: mariadb:11.2.3-jammy
  #   restart: always
  #   volumes:
  #     - fw_pgsql_data:/var/lib/mysql:Z
  #     - .docker/mariadb:/docker-entrypoint-initdb.d
  #   networks:
  #     - fw_network
  #   environment:
  #     MARIADB_ROOT_PASSWORD: root

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - fw_prometheus_data:/prometheus
    networks:
      - fw_network

  grafana:
    image: grafana/grafana:10.1.9-ubuntu
    container_name: grafana
    ports:
      - 9091:3000
    volumes:
      - fw_grafana_data:/var/lib/grafana
    networks:
      - fw_network